sync stable/0.6 with trunk rev.1915

diff --git a/prepare_new_release b/prepare_new_release
--- a/prepare_new_release
+++ b/prepare_new_release
@@ -52,7 +52,8 @@ coinURL="https://projects.coin-or.org/svn"
 # Begin parameter processing.
 
 printHelp=0
-ignoreBuildToolsMismatch=0
+ignoreBuildToolsMismatch=no
+mismatchBTExternals=
 suppressCheckout=0
 
 # stableURL will be the stable branch that is the parent for the release we
@@ -97,7 +98,19 @@ else
   while test $# -gt 0 && test $exitValue = 0 && test $printHelp = 0 ; do
     case "$1" in
       -h* | --h*) printHelp=1 ;;
-      -i* | --i*) ignoreBuildToolsMismatch=1 ;;
+      -i* | --i*)
+	   if expr "$1" : '.*-i.*=.*' 2>&1 >/dev/null ; then
+	     mismatchBTExternals=`echo $1 | sed -n -e 's/[^=]*=\(.*\)/\1/p'`
+	   else
+	     shift
+	     mismatchBTExternals=$1
+	   fi
+	   if test "x$mismatchBTExternals" = "xall" ; then
+	     ignoreBuildToolsMismatch=all
+	   else
+	     ignoreBuildToolsMismatch=partial
+	   fi
+	   ;;
       -p* | --p*) suppressCheckout=1 ;;
       -s* | --s*)
 	   if expr "$1" : '.*-s.*=.*' 2>&1 >/dev/null ; then
@@ -232,11 +245,13 @@ what comes after "https://projects.coin-or.org/svn".  A typical example is
 Options:
   -b <BuildToolsURL>	URL for BuildTools; required to generate a release
   			for a ThirdParty or Data project.
-  -i			Ignore BuildTools version mismatches in externals.
+  -i <projectlist>	Ignore BuildTools version mismatches for the listed
+  			externals (comma-separated list of project names,
+			e.g., -i Osi,Cbc). '-i all' ignores all mismatches.
   -p			Suppress checkout (useful for testing)
   -s <projectlist>      Suppress conversion from stable to release for the
 			listed externals (comma-separated list of project
-			names, e.g., -s Osi,Cbc).
+			names).
   -x <projectlist>	Remove the listed projects from the list of externals
 			(comma-separated list of project names).
 
@@ -552,33 +567,39 @@ if test -n "$srcDepFile" ; then
 	if test -n "$extBTURL" ; then
 	  testResult=`compareURLVersions "$ourBTURL" "$extBTURL"`
 	  if test $testResult = no ; then
-	    echo "    WARNING: BuildTools mismatch: $ext_rel_url_notail uses $extBTURL"
-	    if test $ignoreBuildToolsMismatch = 0 ; then
-	       buildtoolsMismatch=1
+	    if test $ignoreBuildToolsMismatch = all || \
+	       expr "$mismatchBTExternals" : '.*'$ext_proj'.*' 2>&1 >/dev/null ; then
+	      echo "    WARNING: BuildTools mismatch: $ext_url_notail uses $extBTURL"
+	    else
+	      buildtoolsMismatch=1
+	      echo "    ERROR: BuildTools mismatch: $ext_url_notail uses $extBTURL"
 	    fi
 	  fi
 	fi
       fi
-
       echo "$ext_name  $ext_rel_url" >>Dependencies
       ext_name=
       echo ''
     fi
   done
 
-# If we have a BuildTools mismatch, and mismatch is not permitted, exit.
+# If we have a BuildTools mismatch, exit.
 
-  if test $buildtoolsMismatch -gt $ignoreBuildToolsMismatch ; then
+  if test $buildtoolsMismatch = 1 ; then
     echo "Exiting due to BuildTools mismatches; use -i to ignore."
     exit 2
   fi
 
+# Try to check out the externals. Try three times before failing.
   echo ''
   echo '===> Updating svn:externals property and checking out externals ...'
   echo ''
 
   svn propset svn:externals -F Dependencies .
-  svn update
+  svn update ||
+  { echo "Retry 1 ... " ; svn update ; } ||
+  { echo "Retry 2 ... " ; svn update ; } ||
+  { echo "Checkout of externals failed. Aborting." ; exit 3 ; }
 
   if test -d ThirdParty ; then
     echo ''
diff --git a/set_externals b/set_externals
--- a/set_externals
+++ b/set_externals
@@ -35,6 +35,11 @@ printHelp=0
 exitValue=0
 depFile=
 
+# stableExternals specifies externals which we do not want to convert to
+# releases, for whatever reason.
+
+stableExternals=
+
 if test "$#" -eq 0; then
   printHelp=1
 else
@@ -45,7 +50,14 @@ else
   while test $# -gt 0 && test $exitValue = 0 && test $printHelp = 0 ; do
     case "$1" in
       -h* | --h*) printHelp=1 ;;
-           
+      -s* | --s*)
+	   if expr "$1" : '.*-s.*=.*' 2>&1 >/dev/null ; then
+	     stableExternals=`echo $1 | sed -n -e 's/[^=]*=\(.*\)/\1/p'`
+	   else
+	     shift
+	     stableExternals=$1
+	   fi
+	   ;;
        -*) echo "$0: unrecognised command line switch '"$1"'."
 	   printHelp=1
 	   exitValue=1
@@ -58,7 +70,8 @@ else
 fi
 
 # Find the most recent release for each stable external. Allow for the
-# possibility that a stable branch has no associated release.
+# possibility that a stable branch has no associated release, or that the
+# user has asked to keep the stable external.
 
 if test $printHelp = 0 && test $exitValue = 0; then
   if test -r $depFile; then
@@ -81,36 +94,40 @@ if test $printHelp = 0 && test $exitValue = 0; then
           ext_name=
           continue
         fi                                    
-	extType=`extractTypeFromURL $ext_url`
-	if test "$extType" = invalid ; then
-          echo ''
-          echo "The external URL $ext_url appears to be invalid. Exiting."
-          echo ''
-          exit 3
-        fi
-
-	if test "$extType" = stable ; then
-	  ext_majVer=`extractMajorFromURL $ext_url`
-	  ext_minVer=`extractMinorFromURL $ext_url`
-	  ext_rel_url=`bestRelease $ext_url $ext_majVer $ext_minVer`
-	  if test -z "$ext_rel_url" ; then
-	    echo "There is no release for $ext_url"
-	    echo "Keeping $ext_url"
-	  else
-	    # Normal (not BuildTools/ThirdParty/Data) need a directory name,
-	    # and it may differ from the project name. Carefully preserve it.
-	    # ThirdParty URLs include BuildTools ; both named for emphasis
-	    case $ext_rel_url in
-	      */BuildTools/* | */ThirdParty/* | */Data/* ) ;;
-	      *) ext_tail=`extractTailFromExt $ext_url`
-		 ext_rel_url=${ext_rel_url}${ext_tail}
-		 ;;
-	    esac
-	    echo "Replacing $ext_url with $ext_rel_url"
-	    ext_url=$ext_rel_url
-	  fi
+	if expr "$stableExternals" : '.*'"$ext_name"'.*' 2>&1 >/dev/null ; then
+	  echo "    $ext_name $ext_url unchanged"
 	else
-	  echo "Keeping $ext_url"
+	  extType=`extractTypeFromURL $ext_url`
+	  if test "$extType" = invalid ; then
+	    echo ''
+	    echo "The external URL $ext_url appears to be invalid. Exiting."
+	    echo ''
+	    exit 3
+	  fi
+
+	  if test "$extType" = stable ; then
+	    ext_majVer=`extractMajorFromURL $ext_url`
+	    ext_minVer=`extractMinorFromURL $ext_url`
+	    ext_rel_url=`bestRelease $ext_url $ext_majVer $ext_minVer`
+	    if test -z "$ext_rel_url" ; then
+	      echo "There is no release for $ext_url"
+	      echo "Keeping $ext_url"
+	    else
+	      # Normal (not BuildTools/ThirdParty/Data) need a directory name,
+	      # and it may differ from the project name. Carefully preserve it.
+	      # ThirdParty URLs include BuildTools ; both named for emphasis
+	      case $ext_rel_url in
+		*/BuildTools/* | */ThirdParty/* | */Data/* ) ;;
+		*) ext_tail=`extractTailFromExt $ext_url`
+		   ext_rel_url=${ext_rel_url}${ext_tail}
+		   ;;
+	      esac
+	      echo "Replacing $ext_url with $ext_rel_url"
+	      ext_url=$ext_rel_url
+	    fi
+	  else
+	    echo "Keeping $ext_url"
+	  fi
 	fi
 
         echo "$ext_name  $ext_url" >>Externals.releases
@@ -140,18 +157,23 @@ if test $printHelp = 1 ; then
   cat <<EOF
 Usage: set_externals <Dependency File> 
 
+Options:
+  -s <projectlist>      Suppress conversion from stable to release for the
+			listed externals (comma-separated list of project
+			names, e.g., -s Osi,Cbc).
+
 This script takes as input a dependency file containing a list of stable
 versions of COIN projects on separate lines in the form
 
  <name> <URL of stable version>
 
-Recommended practice is to keep this list in a file called "Dependencies" in
-the project's root directory. A temporary file called "Externals.releases" in
-the same form, but with the URL of each stable version replaced by the URL of
-the latest associated release is produced. From this file, the script will
-set the svn:externals variable. It does not do an update or commit the
-change. After the script runs, do an update and test build, then commit the
-change if you are happy.
+Recommended practice is to keep the set of stable externals in a file
+called "Dependencies" in the project's root directory. A temporary file
+called "Externals.releases" in the same form, but with the URL of each
+stable version replaced by the URL of the latest associated release is
+produced. From this file, the script will set the svn:externals variable. It
+does not do an update or commit the change. After the script runs, do an
+update and test build, then commit the change if you are happy.
 
 EOF
 else
